name: tests

on:
  workflow_run:
    workflows: ["Build Check"]
    types:
      - completed

jobs:
  setup-and-generate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run Build
        run: |
          go test -v ./...


